// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOqa1apE6rTvs1cURxIv-vZrFq0s2ek8U',
    appId: '1:193952779418:web:3b4953b91374eabed6a323',
    messagingSenderId: '193952779418',
    projectId: 'rsj-storyverse',
    authDomain: 'rsj-storyverse.firebaseapp.com',
    storageBucket: 'rsj-storyverse.firebasestorage.app',
    measurementId: 'G-EEEQ0ZHEQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkgikMIhQFRVYJ3W4f3wx3G8eBGyKYDc',
    appId: '1:193952779418:android:e00b34dbace7cef9d6a323',
    messagingSenderId: '193952779418',
    projectId: 'rsj-storyverse',
    storageBucket: 'rsj-storyverse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9l_RiAnVg1q0ERj2rWGAbQwJi54_CkGM',
    appId: '1:193952779418:ios:69042b0df9239778d6a323',
    messagingSenderId: '193952779418',
    projectId: 'rsj-storyverse',
    storageBucket: 'rsj-storyverse.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9l_RiAnVg1q0ERj2rWGAbQwJi54_CkGM',
    appId: '1:193952779418:ios:69042b0df9239778d6a323',
    messagingSenderId: '193952779418',
    projectId: 'rsj-storyverse',
    storageBucket: 'rsj-storyverse.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOqa1apE6rTvs1cURxIv-vZrFq0s2ek8U',
    appId: '1:193952779418:web:5fcfdcd9b4a34ad1d6a323',
    messagingSenderId: '193952779418',
    projectId: 'rsj-storyverse',
    authDomain: 'rsj-storyverse.firebaseapp.com',
    storageBucket: 'rsj-storyverse.firebasestorage.app',
    measurementId: 'G-JF0Z6SPE67',
  );
}
